[package]
name = "server"
version = "0.1.0"
authors = ["Keith Bauer <onesadcookie@gmail.com>"]

[dependencies]
dotenv = "~0.13.0"
pretty_env_logger = "~0.2.4"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
warp = "=0.1.5"
lazy_static = "1.1.0"
